stellar/kotlin-wallet-sdk

- README.md
- build.gradle
- src/main/kotlin/Main.kt
- src/main/kotlin/org/stellar/walletsdk/Wallet.kt
- src/test/kotlin/org/stellar/walletsdk/WalletTest.kt
- `Wallet.create()` method to generate account keypair (doesn't depend on the network)
- Added `ktfmt` plugin for code formatting
> Create account keys + ktfmt plugin

- src/main/kotlin/org/stellar/walletsdk/Auth.kt
- src/main/kotlin/org/stellar/walletsdk/WalletSigner.kt
- src/test/kotlin/org/stellar/walletsdk/AuthTest.kt
- src/test/kotlin/org/stellar/walletsdk/InProcessWalletSigner.kt
This is a POC of the WalletSigner interface.
The naming maybe a little rough, so feel free to rename.
> WalletSigner interface implementation POC

- build.gradle
- src/main/kotlin/org/stellar/walletsdk/Wallet.kt
- src/main/kotlin/org/stellar/walletsdk/util/BuildFeeBumpTransaction.kt
- src/main/kotlin/org/stellar/walletsdk/util/BuildTransaction.kt
- src/main/kotlin/org/stellar/walletsdk/util/FetchAccount.kt
- src/main/kotlin/org/stellar/walletsdk/util/ValidateTransaction.kt
- src/test/kotlin/org/stellar/walletsdk/SuspendTest.kt
- src/test/kotlin/org/stellar/walletsdk/WalletTest.kt
- src/test/kotlin/org/stellar/walletsdk/util/BuildFeeBumpTransactionTest.kt
- src/test/kotlin/org/stellar/walletsdk/util/BuildTransactionTest.kt
- src/test/kotlin/org/stellar/walletsdk/util/ValidateTransactionTest.kt
Added suspend methods to make Android happy
> Handle async methods

- src/main/kotlin/org/stellar/walletsdk/Auth.kt
- src/main/kotlin/org/stellar/walletsdk/Wallet.kt
- src/main/kotlin/org/stellar/walletsdk/WalletSigner.kt
- src/main/kotlin/org/stellar/walletsdk/util/AccountAvailableNativeBalance.kt
- src/main/kotlin/org/stellar/walletsdk/util/AccountReservedBalance.kt
- src/main/kotlin/org/stellar/walletsdk/util/BuildFeeBumpTransaction.kt
- src/main/kotlin/org/stellar/walletsdk/util/BuildTransaction.kt
- src/main/kotlin/org/stellar/walletsdk/util/ConvertLumensStroops.kt
- src/main/kotlin/org/stellar/walletsdk/util/CreateDecoratedSignature.kt
- src/main/kotlin/org/stellar/walletsdk/util/CreateTransactionBuilder.kt
- src/main/kotlin/org/stellar/walletsdk/util/FetchAccount.kt
- src/main/kotlin/org/stellar/walletsdk/util/GetRecoveryServerTxnSignature.kt
- src/main/kotlin/org/stellar/walletsdk/util/GsonUtils.kt
- src/main/kotlin/org/stellar/walletsdk/util/OkHttpUtils.kt
- src/main/kotlin/org/stellar/walletsdk/util/Operation.kt
- src/main/kotlin/org/stellar/walletsdk/util/SetRecoveryMethods.kt
- src/main/kotlin/org/stellar/walletsdk/util/SponsorOperation.kt
- src/main/kotlin/org/stellar/walletsdk/util/ValidateTransaction.kt
- src/test/kotlin/org/stellar/walletsdk/AuthTest.kt
First attempt to document classes and methods with KDoc.
> KDoc documentation for classes and methods

- src/main/kotlin/org/stellar/walletsdk/Anchor.kt
- src/main/kotlin/org/stellar/walletsdk/Auth.kt
- src/main/kotlin/org/stellar/walletsdk/Data.kt
- src/main/kotlin/org/stellar/walletsdk/Exception.kt
- src/main/kotlin/org/stellar/walletsdk/util/Sep24InteractiveFlow.kt
- src/main/kotlin/org/stellar/walletsdk/util/StellarToml.kt
- src/test/kotlin/org/stellar/walletsdk/AnchorTest.kt
- src/test/kotlin/org/stellar/walletsdk/ConstantTest.kt
- src/test/kotlin/org/stellar/walletsdk/util/StellarTomlTest.kt
- src/test/resources/account_full.json
Deposit
https://user-images.githubusercontent.com/7346473/198392788-fe222eeb-07db-420a-b8c9-06aaf827a70f.mp4
Withdrawal
https://user-images.githubusercontent.com/7346473/198392842-6022f00c-b11e-473e-9f5b-b33a350b1e7e.mp4
Notes:
- The Android emulator might cause the UI issues we see in the anchor flow. I don't see those issues in the browser.
- The withdrawal process is incomplete (missing sending funds to the anchor step). The demo will be updated when the transaction status method is implemented.
> SEP-24 interactive deposit and withdrawal

- examples/SEP-24/build.gradle.kts
- examples/SEP-24/src/main/kotlin/org/stellar/walletsdk/Main.kt
- settings.gradle.kts
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/Auth.kt
- Added basic examples folder (so we can add more examples later)
- Example of (almost) full SEP-24 flow. 
- Didn't include sending transfer transaction for withdrawal, as it's not yet implemented. 
- Didn't include waiting for deposit transaction, also not implemented yet
> SEP-24 example

- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/Anchor.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/Data.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/util/Sep24InteractiveFlow.kt
- wallet-sdk/src/test/kotlin/org/stellar/walletsdk/AnchorTest.kt
- wallet-sdk/src/test/kotlin/org/stellar/walletsdk/helpers/MapFromTomlFile.kt
- wallet-sdk/src/test/resources/stellar.toml
Added methods to fetch a single transaction and all transactions from an anchor. For now, it is up to the user to store the auth token and Stellar TOML file. We can implement this in the Wallet SDK later if we think it will add value to the user.
> Interactive flow: transaction status + history

- examples/SEP-24/build.gradle.kts
- wallet-sdk/build.gradle.kts
Tested with empty project, no additional dependencies needed anymore
> Fixed library jar

- examples/SEP-24/src/main/kotlin/org/stellar/walletsdk/Main.kt
> Fixed examples

- examples/SEP-24/src/main/kotlin/org/stellar/walletsdk/Main.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/Anchor.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/Auth.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/Wallet.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/util/BuildTransaction.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/util/FetchAccount.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/util/FetchLiquidityPoolInfo.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/util/FormatAccountBalances.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/util/GetRecoveryServerTxnSignature.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/util/Sep24InteractiveFlow.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/util/SetRecoveryMethods.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/util/StellarToml.kt
As per title, removed coroutines. SDK users should decide themself on how to call SDK methods and not being restricted to sync IO dispatcher call.
> Remove coroutines

- examples/SEP-24/src/main/kotlin/org/stellar/walletsdk/Main.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/Auth.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/util/SchemeUtil.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/util/StellarToml.kt
Now localhost can be used. Tested with anchor platform.
> Add localhost support

- LICENSE
- build.gradle.kts
- wallet-sdk/build.gradle.kts
Configured publishing to maven central
> Setup maven publish

- examples/SEP-24/src/main/kotlin/org/stellar/walletsdk/Main.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/Data.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/Wallet.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/anchor/Data.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/exception/StellarExceptions.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/extension/Transaction.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/recovery/Data.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/recovery/Recovery.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/util/GlobalConfig.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/util/Util.kt
- wallet-sdk/src/test/kotlin/org/stellar/walletsdk/WalletTest.kt
- wallet-sdk/src/test/kotlin/org/stellar/walletsdk/util/CreateDecoratedSignatureTest.kt
Added method for asset transfer + finished SEP-24 example
> Add transfer method

- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/recovery/Recovery.kt
- wallet-sdk/src/testIntegration/kotlin/org/stellar/walletsdk/Test.kt
While updating the Android app demo, I noticed that some things were breaking for account recovery.
> Account recovery fixes

- README.md
- build.gradle.kts
- examples/SEP-24/src/main/kotlin/org/stellar/example/Main.kt
- examples/documentation/build.gradle.kts
- examples/documentation/src/example-basic-01.kt
- gradle/libs.versions.toml
- knit.properties
- settings.gradle.kts
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/Wallet.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/horizon/Account.kt
Basic knit example with updated README using [knit](https://github.com/Kotlin/kotlinx-knit) tool
> Add knit docs

- docs/WalletGuide.md
- examples/SEP-24/src/main/kotlin/org/stellar/example/Main.kt
- examples/documentation/src/example-anchor-01.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/Wallet.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/anchor/Anchor.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/anchor/Interactive.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/exception/AnchorExceptions.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/horizon/TransactionBuilder.kt
- wallet-sdk/src/test/kotlin/org/stellar/walletsdk/SubmitTransactionTest.kt
- wallet-sdk/src/test/kotlin/org/stellar/walletsdk/account/AddRemoveAssetTest.kt
- wallet-sdk/src/test/kotlin/org/stellar/walletsdk/account/AddRemoveSignerTest.kt
- wallet-sdk/src/test/kotlin/org/stellar/walletsdk/account/CreateAndFundTest.kt
- wallet-sdk/src/test/kotlin/org/stellar/walletsdk/account/LockAccountMasterKeyTest.kt
- wallet-sdk/src/test/kotlin/org/stellar/walletsdk/anchor/GetInteractiveFlowTest.kt
- wallet-sdk/src/test/kotlin/org/stellar/walletsdk/anchor/GetServicesInfoTest.kt
- wallet-sdk/src/test/kotlin/org/stellar/walletsdk/recovery/RegisterSignersTest.kt
- wallet-sdk/src/testIntegration/kotlin/org/stellar/walletsdk/RecoveryTest.kt
Now info is cached and not needed to be re-fetched every time
> Cleanup info

- examples/SEP-24/src/main/kotlin/org/stellar/example/Main.kt
- gradle/libs.versions.toml
- wallet-sdk/build.gradle.kts
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/Data.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/anchor/AnchorTransaction.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/horizon/Stellar.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/json/AnchorDeserializers.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/util/Format.kt
- wallet-sdk/src/testIntegration/kotlin/org/stellar/walletsdk/AnchorPlatformTest.kt
Tests to run with https://github.com/stellar/java-stellar-anchor-sdk/pull/709
> Add AP tests

- build.gradle.kts
- gradle/libs.versions.toml
Release 0.4 and fix dokka (need to downgrade)
> [WAL-605] [WAL-607] 0.4.0

- wallet-sdk/src/testIntegration/kotlin/org/stellar/walletsdk/AnchorPlatformTest.kt
Small changes for easier withdrawal test
> Small changes in AP tests

- docs/WalletGuide.md
- examples/SEP-24/src/main/kotlin/org/stellar/example/Main.kt
- examples/documentation/src/example-anchor-01.kt
- examples/documentation/src/example-client-domain-01.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/Wallet.kt
- wallet-sdk/src/test/kotlin/org/stellar/walletsdk/anchor/GetInfoTest.kt
- wallet-sdk/src/test/kotlin/org/stellar/walletsdk/anchor/GetInteractiveFlowTest.kt
- wallet-sdk/src/test/kotlin/org/stellar/walletsdk/anchor/GetServicesInfoTest.kt
- wallet-sdk/src/testIntegration/kotlin/org/stellar/walletsdk/AnchorPlatformTest.kt
For some reason change from [this comment](https://github.com/stellar/kotlin-wallet-sdk/pull/78#discussion_r1131617874) didn't make it into final version. I lost my commit that was not pushed and re-created this change
> WAL-573: Fix comment

- build.gradle.kts
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/anchor/Anchor.kt
- wallet-sdk/src/testIntegration/kotlin/org/stellar/walletsdk/AnchorPlatformTest.kt
Also add more tests for the anchor platform
> [WAL-755] Improve transactions queries

- docs/WalletGuide.md
- examples/SEP-24/src/main/kotlin/org/stellar/example/Main.kt
- examples/documentation/src/example-transaction-01.kt
- examples/documentation/src/example-transaction-02.kt
- examples/documentation/src/example-transaction-03.kt
- examples/documentation/src/example-transaction-04.kt
- examples/documentation/src/example-transaction-05.kt
- examples/documentation/src/example-transaction-06.kt
- examples/documentation/src/example-transaction-xdr-01.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/Wallet.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/horizon/Stellar.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/horizon/transaction/TransactionBuilder.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/util/Util.kt
- wallet-sdk/src/test/kotlin/org/stellar/walletsdk/SubmitTransactionTest.kt
- wallet-sdk/src/test/resources/expired_transaction.json
Add handler for https://github.com/stellar/java-stellar-sdk/blob/master/src/main/java/org/stellar/sdk/Server.java#L282
> [WAL-868] Improve transaction submission

- build.gradle.kts
- examples/SEP-24/src/main/kotlin/org/stellar/example/Main.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/anchor/Interactive.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/exception/AnchorExceptions.kt
This adds XLM support for the SEP-24 client.
> [ANCHOR-305] Add support for native assets

- docs/WalletGuide.md
- examples/MGI/src/main/kotlin/org/stellar/example/Deposit.kt
- examples/MGI/src/main/kotlin/org/stellar/example/GetTransaction.kt
- examples/MGI/src/main/kotlin/org/stellar/example/Withdrawal.kt
- examples/SEP-24/src/main/kotlin/org/stellar/example/Main.kt
- examples/documentation/src/example-anchor-01.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/anchor/Interactive.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/auth/Auth.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/auth/Data.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/auth/WalletSigner.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/json/AnchorDeserializers.kt
- wallet-sdk/src/test/kotlin/org/stellar/walletsdk/anchor/GetInteractiveFlowTest.kt
- wallet-sdk/src/testIntegration/kotlin/org/stellar/walletsdk/AnchorPlatformTest.kt
1. Parse token and validate expiration time
2. Don’t pass account to interactive flow when it’s not necessary
> [WAL-888] Improve auth token handling

- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/anchor/Anchor.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/anchor/Interactive.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/auth/Auth.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/exception/WalletException.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/json/Json.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/recovery/AccountRecover.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/recovery/Recovery.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/util/Util.kt
* Try to deserialize error response 
* If fails, preserve original response string
> [WAL-731] Improve error handling

- config/detekt/detekt.yml
- docs/WalletGuide.md
- examples/SEP-24/src/main/kotlin/org/stellar/example/Main.kt
- examples/documentation/src/example-anchor-01.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/anchor/Anchor.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/anchor/AnchorTransaction.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/anchor/TransactionStatus.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/anchor/Watcher.kt
Add watcher class that allows to watch transaction status updates.
Example of usage:
```kotlin
suspend fun watchTransaction() {
val watcher = anchor.watcher()
val result = watcher.watchOneTransaction(getAuthToken(), "transaction id")
do {
val event = result.channel.receive()
when (event) {
is StatusChange ->
println("Status changed to ${event.status}. Transaction: ${event.transaction}")
is ChannelClosed -> println("Channel closed. Job is done")
is ExceptionHandlerExit -> println("Exception handler exited the job")
}
} while (event !is ChannelClosed)
}
```
> [WAL-916] Watcher implementation

- docs/WalletGuide.md
- examples/MGI/src/main/kotlin/org/stellar/example/Deposit.kt
- examples/MGI/src/main/kotlin/org/stellar/example/Info.kt
- examples/MGI/src/main/kotlin/org/stellar/example/Withdrawal.kt
- examples/SEP-24/src/main/kotlin/org/stellar/example/Main.kt
- examples/documentation/src/example-anchor-01.kt
- examples/documentation/src/example-client-domain-01.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/anchor/Anchor.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/anchor/Interactive.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/anchor/InteractriveFlow.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/anchor/Sep24.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/auth/Sep10.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/customer/Sep12.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/recovery/Recovery.kt
- wallet-sdk/src/test/kotlin/org/stellar/walletsdk/AuthTest.kt
- wallet-sdk/src/test/kotlin/org/stellar/walletsdk/CustomerManagementTest.kt
- wallet-sdk/src/test/kotlin/org/stellar/walletsdk/anchor/GetServicesInfoTest.kt
- wallet-sdk/src/test/kotlin/org/stellar/walletsdk/customer/CustomerTest.kt
- wallet-sdk/src/testIntegration/kotlin/org/stellar/walletsdk/AnchorPlatformTest.kt
All functions with SEP-24 functionality has been moved to `Interactive` class (responsible for SEP-24)
Also, added SEP12 alias for Customer class/function
> [WAL-944] Reorganization

- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/horizon/Stellar.kt
Add limitation to the fee being payed in the resubmitting with fee bump method
> Add max fee limit to submit method

- build.gradle.kts
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/Wallet.kt
> Function alias to use HTTP by default 

- build.gradle.kts
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/auth/Sep10.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/exception/StellarExceptions.kt
- wallet-sdk/src/main/kotlin/org/stellar/walletsdk/horizon/Stellar.kt
It's a bit hard to debug what operation failed based by just operation codes. Added transaction XDR in error message for easier debug
> [WAL-1381] Expand error message of TransactionSubmitFailedException

- .github/workflows/codeql.yml
Added workflow file for running code scanning through CodeQL on pull requests and pushes to main branch.
> Add CodeQL config

- .github/workflows/on_release_created_or_updated.yml
- Removed unused print action
- Add `published` trigger to `on.release`
> [HOTFIX] Removed unused print action
